name: Discord webhook

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 4"  # Every Thursday at 01:00 PM (KST)

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install fonts
        run: |
          sudo apt update
          sudo apt install -y fonts-nanum

      - name: Run Python scripts
        env:
          API_KEY: ${{ secrets.API_KEY }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          if [ -f main.py ]; then python main.py; fi

      - uses: liskin/gh-workflow-keepalive@v1
